// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: s07-0/bot.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	TelegramId           string   `protobuf:"bytes,4,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d70c2c9cd41fe1, []int{0}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetTelegramId() string {
	if m != nil {
		return m.TelegramId
	}
	return ""
}

// Balance 余额信息
type Balance struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d70c2c9cd41fe1, []int{1}
}
func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Balance) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type SendMessageRequest struct {
	ChatId               int64    `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d70c2c9cd41fe1, []int{2}
}
func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *SendMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SendMessageResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId            string   `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d70c2c9cd41fe1, []int{3}
}
func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(m, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

func (m *SendMessageResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendMessageResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "proto.UserInfo")
	proto.RegisterType((*Balance)(nil), "proto.Balance")
	proto.RegisterType((*SendMessageRequest)(nil), "proto.SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "proto.SendMessageResponse")
}

func init() { proto.RegisterFile("s07-0/bot.proto", fileDescriptor_d5d70c2c9cd41fe1) }

var fileDescriptor_d5d70c2c9cd41fe1 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4f, 0x2b, 0x31,
	0x0c, 0x80, 0x5f, 0x5f, 0x7f, 0x9e, 0x3b, 0x20, 0x19, 0x04, 0x47, 0x25, 0x44, 0x75, 0x53, 0x17,
	0xda, 0x0a, 0x86, 0x4e, 0x0c, 0x74, 0x40, 0xba, 0x01, 0x86, 0x2b, 0x2c, 0x2c, 0x28, 0x4d, 0x4c,
	0xa9, 0xd4, 0x4b, 0x4a, 0x9c, 0xab, 0xe0, 0xbf, 0x47, 0xc9, 0xdd, 0x55, 0x45, 0x30, 0xc5, 0x9f,
	0x6d, 0x7d, 0xb6, 0x03, 0x47, 0x3c, 0x9d, 0x5d, 0x4d, 0x27, 0x4b, 0xe3, 0xc6, 0x5b, 0x6b, 0x9c,
	0xc1, 0x76, 0x78, 0x92, 0x1d, 0xf4, 0x9e, 0x99, 0x6c, 0xaa, 0xdf, 0x0c, 0x9e, 0x41, 0xb7, 0x60,
	0xb2, 0xaf, 0x6b, 0x15, 0x37, 0x86, 0x8d, 0x51, 0x33, 0xeb, 0x78, 0x4c, 0x15, 0x0e, 0xa0, 0xe7,
	0x23, 0x2d, 0x72, 0x8a, 0xff, 0x0f, 0x1b, 0xa3, 0x28, 0xdb, 0x33, 0x9e, 0x40, 0x9b, 0x72, 0xb1,
	0xde, 0xc4, 0xcd, 0x50, 0x28, 0x01, 0x2f, 0xa1, 0xef, 0x68, 0x43, 0x2b, 0x2b, 0x72, 0xaf, 0x6b,
	0x85, 0x1a, 0xd4, 0xa9, 0x54, 0x25, 0xb7, 0xd0, 0x9d, 0x8b, 0x8d, 0xd0, 0x92, 0xbc, 0x5d, 0x16,
	0xd6, 0x92, 0x96, 0x5f, 0x61, 0x6e, 0x94, 0xed, 0x19, 0x4f, 0xa1, 0x23, 0x72, 0x53, 0x68, 0x57,
	0xcd, 0xad, 0x28, 0xb9, 0x03, 0x5c, 0x90, 0x56, 0x0f, 0xc4, 0x2c, 0x56, 0x94, 0xd1, 0x47, 0x41,
	0xec, 0xfc, 0x01, 0xf2, 0x5d, 0xb8, 0x83, 0x03, 0x3c, 0xa6, 0x0a, 0x11, 0x5a, 0x8e, 0x3e, 0x6b,
	0x49, 0x88, 0x93, 0x47, 0x38, 0xfe, 0xa1, 0xe0, 0xad, 0xd1, 0x4c, 0x18, 0x43, 0x97, 0x0b, 0x29,
	0x89, 0x39, 0x38, 0x7a, 0x59, 0x8d, 0x78, 0x01, 0x90, 0x97, 0xcd, 0x7e, 0x40, 0xa9, 0x8a, 0xaa,
	0x4c, 0xaa, 0xae, 0x9f, 0x00, 0xe6, 0xc6, 0x2d, 0xc8, 0xee, 0xd6, 0x92, 0xf0, 0x1e, 0xfa, 0x07,
	0x76, 0x3c, 0x2f, 0x7f, 0x7d, 0xfc, 0x7b, 0xe9, 0xc1, 0xe0, 0xaf, 0x52, 0xb9, 0x4c, 0xf2, 0x6f,
	0xde, 0x7f, 0x89, 0x78, 0x3a, 0x9b, 0x84, 0x96, 0x65, 0x27, 0x3c, 0x37, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x6f, 0xb6, 0xb2, 0xb3, 0xcd, 0x01, 0x00, 0x00,
}
