// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/bot.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserType int32

const (
	UserType_fame  UserType = 0
	UserType_Women UserType = 1
)

var UserType_name = map[int32]string{
	0: "fame",
	1: "Women",
}

var UserType_value = map[string]int32{
	"fame":  0,
	"Women": 1,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_05a8af1b83caf9c9, []int{0}
}

type UserInfo struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	TelegramId           string   `protobuf:"bytes,4,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a8af1b83caf9c9, []int{0}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetTelegramId() string {
	if m != nil {
		return m.TelegramId
	}
	return ""
}

// Balance 余额信息
type Balance struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a8af1b83caf9c9, []int{1}
}
func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Balance) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type BaseMsg struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseMsg) Reset()         { *m = BaseMsg{} }
func (m *BaseMsg) String() string { return proto.CompactTextString(m) }
func (*BaseMsg) ProtoMessage()    {}
func (*BaseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a8af1b83caf9c9, []int{2}
}
func (m *BaseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseMsg.Unmarshal(m, b)
}
func (m *BaseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseMsg.Marshal(b, m, deterministic)
}
func (m *BaseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseMsg.Merge(m, src)
}
func (m *BaseMsg) XXX_Size() int {
	return xxx_messageInfo_BaseMsg.Size(m)
}
func (m *BaseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BaseMsg proto.InternalMessageInfo

func (m *BaseMsg) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BaseMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetMessageRps struct {
	BaseMsg              *BaseMsg `protobuf:"bytes,1,opt,name=baseMsg,proto3" json:"baseMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageRps) Reset()         { *m = GetMessageRps{} }
func (m *GetMessageRps) String() string { return proto.CompactTextString(m) }
func (*GetMessageRps) ProtoMessage()    {}
func (*GetMessageRps) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a8af1b83caf9c9, []int{3}
}
func (m *GetMessageRps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageRps.Unmarshal(m, b)
}
func (m *GetMessageRps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageRps.Marshal(b, m, deterministic)
}
func (m *GetMessageRps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageRps.Merge(m, src)
}
func (m *GetMessageRps) XXX_Size() int {
	return xxx_messageInfo_GetMessageRps.Size(m)
}
func (m *GetMessageRps) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageRps.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageRps proto.InternalMessageInfo

func (m *GetMessageRps) GetBaseMsg() *BaseMsg {
	if m != nil {
		return m.BaseMsg
	}
	return nil
}

type GetMessageResp struct {
	ChatId               int64    `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageResp) Reset()         { *m = GetMessageResp{} }
func (m *GetMessageResp) String() string { return proto.CompactTextString(m) }
func (*GetMessageResp) ProtoMessage()    {}
func (*GetMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a8af1b83caf9c9, []int{4}
}
func (m *GetMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageResp.Unmarshal(m, b)
}
func (m *GetMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageResp.Marshal(b, m, deterministic)
}
func (m *GetMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageResp.Merge(m, src)
}
func (m *GetMessageResp) XXX_Size() int {
	return xxx_messageInfo_GetMessageResp.Size(m)
}
func (m *GetMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageResp proto.InternalMessageInfo

func (m *GetMessageResp) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *GetMessageResp) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SendMessageRequest struct {
	ChatId               int64    `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a8af1b83caf9c9, []int{5}
}
func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *SendMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SendMessageResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId            string   `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a8af1b83caf9c9, []int{6}
}
func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(m, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

func (m *SendMessageResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendMessageResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.UserType", UserType_name, UserType_value)
	proto.RegisterType((*UserInfo)(nil), "proto.UserInfo")
	proto.RegisterType((*Balance)(nil), "proto.Balance")
	proto.RegisterType((*BaseMsg)(nil), "proto.BaseMsg")
	proto.RegisterType((*GetMessageRps)(nil), "proto.GetMessageRps")
	proto.RegisterType((*GetMessageResp)(nil), "proto.GetMessageResp")
	proto.RegisterType((*SendMessageRequest)(nil), "proto.SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "proto.SendMessageResponse")
}

func init() { proto.RegisterFile("proto/bot.proto", fileDescriptor_05a8af1b83caf9c9) }

var fileDescriptor_05a8af1b83caf9c9 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xcd, 0x92, 0xaf, 0xcd, 0x44, 0x2d, 0xd1, 0x50, 0x20, 0x44, 0x42, 0xad, 0x7c, 0x8a, 0x38,
	0x34, 0x52, 0x39, 0x21, 0xd4, 0x03, 0x3d, 0x00, 0x7b, 0x28, 0x87, 0x2d, 0x08, 0x89, 0x0b, 0x72,
	0xec, 0x69, 0x88, 0x14, 0xdb, 0xcb, 0x8e, 0xb7, 0xa2, 0xff, 0x83, 0x1f, 0x8c, 0xec, 0x75, 0x42,
	0xaa, 0x70, 0xe1, 0xe4, 0x79, 0x33, 0x7e, 0x6f, 0x9e, 0x9f, 0xe1, 0x71, 0x55, 0x3b, 0xef, 0x16,
	0x4b, 0xe7, 0xcf, 0x63, 0x85, 0xfd, 0x78, 0x88, 0x3b, 0xc8, 0xbf, 0x30, 0xd5, 0x85, 0xbd, 0x75,
	0xf8, 0x1c, 0x86, 0x0d, 0x53, 0xfd, 0x7d, 0xad, 0xa7, 0xd9, 0x59, 0x36, 0xef, 0x96, 0x83, 0x00,
	0x0b, 0x8d, 0x33, 0xc8, 0x43, 0x65, 0xa5, 0xa1, 0xe9, 0xa3, 0xb3, 0x6c, 0x3e, 0x2a, 0x77, 0x18,
	0x4f, 0xa0, 0x4f, 0x46, 0xae, 0x37, 0xd3, 0x6e, 0x1c, 0xb4, 0x00, 0x4f, 0x61, 0xec, 0x69, 0x43,
	0xab, 0x5a, 0x9a, 0x20, 0xd7, 0x8b, 0x33, 0xd8, 0xb6, 0x0a, 0x2d, 0x2e, 0x61, 0x78, 0x25, 0x37,
	0xd2, 0x2a, 0x0a, 0xea, 0xaa, 0xa9, 0x6b, 0xb2, 0xea, 0x3e, 0xee, 0x1d, 0x95, 0x3b, 0x8c, 0xcf,
	0x60, 0x20, 0x8d, 0x6b, 0xac, 0x4f, 0x7b, 0x13, 0x12, 0x8b, 0x40, 0x67, 0xba, 0xe6, 0x15, 0x22,
	0xf4, 0x94, 0xd3, 0x94, 0x2c, 0xc7, 0x1a, 0x27, 0xd0, 0x35, 0xbc, 0x4a, 0x9c, 0x50, 0x8a, 0x37,
	0x70, 0xf4, 0x81, 0xfc, 0x35, 0x31, 0xcb, 0x15, 0x95, 0x15, 0xe3, 0x1c, 0x86, 0xcb, 0x56, 0x21,
	0x32, 0xc7, 0x17, 0xc7, 0x6d, 0x30, 0xe7, 0x49, 0xb7, 0xdc, 0x8e, 0xc5, 0x25, 0x1c, 0xef, 0x51,
	0x89, 0xab, 0x10, 0x94, 0xfa, 0x21, 0xfd, 0x5e, 0x50, 0x01, 0x16, 0x3a, 0x78, 0xf1, 0xf4, 0x6b,
	0x6b, 0x36, 0xd6, 0xe2, 0x1d, 0xe0, 0x0d, 0x59, 0xbd, 0xe3, 0xff, 0x6c, 0x88, 0xfd, 0xff, 0x49,
	0x7c, 0x82, 0x27, 0x0f, 0x24, 0xb8, 0x72, 0x96, 0x09, 0xa7, 0x30, 0xe4, 0x46, 0x29, 0x62, 0x8e,
	0x1a, 0x79, 0xb9, 0x85, 0xf8, 0x12, 0xc0, 0xb4, 0x97, 0xc3, 0x82, 0x56, 0x6a, 0x94, 0x3a, 0x85,
	0x7e, 0x75, 0xda, 0x7e, 0xfa, 0xe7, 0xfb, 0x8a, 0x30, 0x87, 0xde, 0xad, 0x34, 0x34, 0xe9, 0xe0,
	0x08, 0xfa, 0x5f, 0x9d, 0x21, 0x3b, 0xc9, 0x2e, 0x7e, 0x67, 0x70, 0xf4, 0x51, 0x5a, 0xbd, 0xa1,
	0x1b, 0xaa, 0xef, 0xd6, 0x8a, 0xf0, 0x3d, 0x8c, 0xf7, 0x2c, 0xe0, 0x8b, 0x14, 0xd6, 0xe1, 0xcb,
	0x66, 0xb3, 0x7f, 0x8d, 0x5a, 0xc7, 0xa2, 0x83, 0x6f, 0x01, 0xfe, 0x86, 0x89, 0x27, 0xe9, 0xee,
	0x83, 0xaf, 0x99, 0x3d, 0x3d, 0xec, 0x12, 0x57, 0xa2, 0x73, 0x95, 0x7f, 0x1b, 0x2c, 0xe2, 0x68,
	0x39, 0x88, 0xc7, 0xeb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x85, 0xbb, 0xa4, 0xd7, 0x02,
	0x00, 0x00,
}
